version: "3.7"

services:
#  mongodb:
#    image : mongo
#    container_name: mongodb
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=conjoined-balcony-mounted-populace-open-slimy-basis-alone
#    volumes:
#      - ./database:/data/db
#    ports:
#      - 27017:27017
#    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: always
    command: caddy file-server --root /srv --listen :80
    ports:
      - "8070:80"
      - "8071:443"
    volumes:
      # - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/files:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
